# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bloc', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='field',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='presence',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.ClassRoom'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
